import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiFastapi,
  SiLaravel,
  SiPostgresql,
  SiMysql,
  SiDocker,
  SiGit,
  SiLinux,
  SiPhp,
  SiBootstrap,
  SiTailwindcss,
  SiJquery,
  SiFirebase,
  SiPostman,
  SiJupyter,
  SiEclipseide,
  SiRender,
  SiRstudioide,
  SiDaisyui,
  SiGooglegemini,
  SiGoogle,
} from "react-icons/si";
import { FaDatabase, FaAws, FaJava } from "react-icons/fa";

export const iconMap = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  react: SiReact,
  nextjs: SiNextdotjs,
  html5: SiHtml5,
  css3: SiCss,
  nodejs: SiNodedotjs,
  fastapi: SiFastapi,
  laravel: SiLaravel,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  docker: SiDocker,
  aws: FaAws,
  git: SiGit,
  linux: SiLinux,
  database: FaDatabase,
  php: SiPhp,
  java: FaJava,
  bootstrap: SiBootstrap,
  tailwindcss: SiTailwindcss,
  jquery: SiJquery,
  firebase: SiFirebase,
  postman: SiPostman,
  jupyter: SiJupyter,
  eclipse: SiEclipseide,
  render: SiRender,
  rstudio: SiRstudioide,
  daisyui: SiDaisyui,
  gemini: SiGooglegemini,
  google: SiGoogle,
};

